
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */




public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    String  p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13;
    public receipt()
    {
        initComponents();
    }
    public receipt(String x1,String x2,String x3,String x4,String x5,String x6,String x7,String x8,String x9,String x10,String x11,String x12,String x13) {
        p1=x1;
        p2=x2;
        p3=x3;
        p4=x4;
        p5=x5;
        p6=x6;
        p7=x7;
        p8=x8;
        p9=x9;
        p10=x10;
        p11=x11;
        p12=x12;
        p13=x13;
        initComponents();
        rc_txt.setText("***********************************************************\n*********************Money Receipt*************************\n***********************************************************\n\n\n");
        rc_txt.setText(rc_txt.getText()+"Senders Name            : "+p1+"\n");
        rc_txt.setText(rc_txt.getText()+"Senders Address        : "+p2+"\n");
        rc_txt.setText(rc_txt.getText()+"Senders Phone No.    : "+p3+"\n");
        rc_txt.setText(rc_txt.getText()+"Receivers Name          : "+p4+"\n");
        rc_txt.setText(rc_txt.getText()+"Receivers Address      : "+p5+"\n");
        rc_txt.setText(rc_txt.getText()+"Receivers Phone No.  : "+p6+"\n");
        rc_txt.setText(rc_txt.getText()+"From                          : "+p7+"\n");
        rc_txt.setText(rc_txt.getText()+"To                             : "+p8+"\n");
        rc_txt.setText(rc_txt.getText()+"Content                     : "+p9+"\n");
        rc_txt.setText(rc_txt.getText()+"Shipment Type          : "+p10+"\n");
        rc_txt.setText(rc_txt.getText()+"Weight                      : "+p11+" KG\n");
        rc_txt.setText(rc_txt.getText()+"Courier Code            : "+p12+"\n");
        rc_txt.setText(rc_txt.getText()+"Package Type            : "+p13+"\n");
        rc_txt.setText(rc_txt.getText()+"***********************************************************\n");
        if(p13=="Gold")
            rc_txt.setText(rc_txt.getText()+"Total :                                             800 BDT\n");
        else
            rc_txt.setText(rc_txt.getText()+"Total :                                             500 BDT\n");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rc_txt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rc_txt.setEditable(false);
        rc_txt.setColumns(20);
        rc_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rc_txt.setRows(5);
        jScrollPane1.setViewportView(rc_txt);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Print Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try
        {
            rc_txt.print();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    String  v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new receipt().setVisible(true);
            }
        });
        
        
        
      
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea rc_txt;
    // End of variables declaration//GEN-END:variables
}
