
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

   

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
    
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    DefaultTableModel model = new DefaultTableModel();
    
    
    public Update()  {
        initComponents();
        conn = admin_panel.ConnectDb();
        Object col[]={"Senders_Name","Senders_Address","Senders_Phone","Receivers_Name","Receivers_Address","Receivers_Phone"};
        model.setColumnIdentifiers(col);
        update_table.setModel(model);
        updatetable2();
        
    }

     public void updatetable2()
     {
         DefaultTableModel dm = (DefaultTableModel)update_table.getModel();
        while(dm.getRowCount() > 0)
        {
            dm.removeRow(0);
        }
        conn=Update.ConnectDb();
        if(conn!=null)
        {
            String sql="SELECT Senders_Name,Senders_Address,Senders_Phone,Receivers_Name,Receivers_Address,Receivers_Phone from order_info";
            try
            { 
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Object columnData [] = new Object[6];
                while(rs.next())
                {
                    columnData[0]=rs.getString("Senders_Name");
                    columnData[1]=rs.getString("Senders_Address");
                    columnData[2]=rs.getString("Senders_Phone");
                    columnData[3]=rs.getString("Receivers_Name");
                    columnData[4]=rs.getString("Receivers_Address");
                    columnData[5]=rs.getString("Receivers_Phone");
                    model.addRow(columnData);
                    
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
     }
     public static Connection ConnectDb()
    {
        try
        {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:mydb.db");
            System.out.println("connected");
            return conn;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            return null;
        }
    }
      
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_1_up = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_2c_up = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_3_up = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_4_up = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_5_up = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_6_up = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        update_table = new javax.swing.JTable();
        updated_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Senders Name");

        txt_1_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Senders Address");

        txt_2c_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_2c_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_2c_upActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Senders Phone No");

        txt_3_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Receivers Name");

        txt_4_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Receivers Address");

        txt_5_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Receivers Phone No");

        txt_6_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_6_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_6_upActionPerformed(evt);
            }
        });

        update_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Senders Name", "Senders Address", "Senders Phone", "Receivers Name", "Receivers Address", "Receivers Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        update_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(update_table);

        updated_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updated_btn.setText("Update");
        updated_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updated_btnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updated_btn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(20, 20, 20)
                            .addComponent(txt_6_up))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_2c_up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                .addComponent(txt_3_up)
                                .addComponent(txt_1_up)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_4_up)
                                .addComponent(txt_5_up)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_1_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_2c_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_3_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_4_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_5_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_6_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updated_btn)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void txt_2c_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_2c_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_2c_upActionPerformed

    private void txt_6_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_6_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_6_upActionPerformed

    String r1,r2,r3,r4,r5,r6,code_r;
    private void update_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_tableMouseClicked
        // TODO add your handling code here:
        
        try
        {
            int row=update_table.getSelectedRow();
            String Table_click=update_table.getModel().getValueAt(row,2).toString();
            String sql="select * from order_info where Senders_Phone = '"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                r1=rs.getString("Senders_Name");
                r2=rs.getString("Senders_Address");
                r3=rs.getString("Senders_Phone");
                r4=rs.getString("Receivers_Name");
                r5=rs.getString("Receivers_Address");
                r6=rs.getString("Receivers_Phone");
                code_r=rs.getString("Code");
                
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        txt_1_up.setText(r1);
        txt_2c_up.setText(r2);
        txt_3_up.setText(r3);
        txt_4_up.setText(r4);
        txt_5_up.setText(r5);
        txt_6_up.setText(r6);
        
    }//GEN-LAST:event_update_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updated_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updated_btnActionPerformed
        // TODO add your handling code here:
        
        String s1,s2,s3,s4,s5,s6;
        s1=txt_1_up.getText();
        s2=txt_2c_up.getText();
        s3=txt_3_up.getText();
        s4=txt_4_up.getText();
        s5=txt_5_up.getText();
        s6=txt_6_up.getText();
        
        
        String sql="UPDATE order_info SET Senders_Name ='"+s1+"' , Senders_Address = '"+s2+"', Senders_Phone = '"+s3+"',Receivers_Name = '"+s4+"',Receivers_Address = '"+s5+"',Receivers_Phone =  '"+s6+"' WHERE Code ='"+code_r+"' ";
        
        try
        {
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated!!");
            pst.close();
            rs.close();
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        updatetable2();
    }//GEN-LAST:event_updated_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Update().setVisible(true);
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_1_up;
    private javax.swing.JTextField txt_2c_up;
    private javax.swing.JTextField txt_3_up;
    private javax.swing.JTextField txt_4_up;
    private javax.swing.JTextField txt_5_up;
    private javax.swing.JTextField txt_6_up;
    private javax.swing.JTable update_table;
    private javax.swing.JButton updated_btn;
    // End of variables declaration//GEN-END:variables
}
